# Generated by Django 5.0.7 on 2024-08-01 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_notifications', '0006_emailnewsnotification_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockemailnotification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Stock email notification', 'verbose_name_plural': 'Stock email notifications'},
        ),
    ]
